import React, { useState } from 'react';
import { Modal, View, Text, TouchableOpacity, ScrollView, Alert } from 'react-native';
import { Transaction, DashboardStats, TRANSLATIONS, Language, convertAmount, TransactionType, getLocalizedCategory } from '../types';
import { X, Share2, FileText, Copy, CheckCircle2, Mail, MessageCircle } from 'lucide-react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { safeCopy } from '../utils/clipboard';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  transactions: Transaction[];
  stats: DashboardStats;
  profileName: string;
  currency: string;
  language: Language;
  soundEnabled: boolean;
}

export const ShareModal: React.FC<Props> = ({
  isOpen,
  onClose,
  transactions,
  stats,
  profileName,
  currency,
  language,
}) => {
  const [copied, setCopied] = useState(false);
  const t = TRANSLATIONS[language].share;

  if (!isOpen) return null;

  const formatCurrency = (amount: number) => {
    // Simple formatter for RN
    return `${currency} ${amount.toFixed(2)}`;
  };

  const getExpenseBreakdown = () => {
    const categoryMap = new Map<string, number>();
    transactions
        .filter(t => t.type === TransactionType.EXPENSE)
        .forEach(t => {
            const convertedVal = convertAmount(t.amount, t.currency || 'USD', currency);
            const catName = getLocalizedCategory(t.category, language);
            categoryMap.set(catName, (categoryMap.get(catName) || 0) + convertedVal);
        });

    const sortedCategories = Array.from(categoryMap.entries()).sort((a, b) => b[1] - a[1]);
    const title = language === 'bn' ? 'খরচের বিবরণ:' : 'Expense Breakdown:';
    const lines = sortedCategories.map(([cat, amount]) => `• ${cat}: ${formatCurrency(amount)}`);
    return sortedCategories.length > 0 ? `\n${title}\n${lines.join('\n')}` : "";
  };

  const getSummaryText = () => {
    const breakdown = getExpenseBreakdown();
    return `📊 *Hisab Report* (${profileName})
---------------------------
💰 ${t.totalBalance}: ${formatCurrency(stats.balance)}
📈 ${t.netIncome}: ${formatCurrency(stats.totalIncome)}
📉 ${t.netExpense}: ${formatCurrency(stats.totalExpense)}
---------------------------
${breakdown}

Generated by Hisab`.trim();
  };

  const generateAndSharePDF = async () => {
    const expenseRows = transactions
      .filter(t => t.type === TransactionType.EXPENSE)
      .slice(0, 10)
      .map(t => `<tr><td>${getLocalizedCategory(t.category, language)}</td><td>${formatCurrency(t.amount)}</td></tr>`)
      .join('');

    const html = `
      <html>
        <head>
          <style>
            body { font-family: Helvetica, sans-serif; padding: 20px; }
            h1 { color: #16a34a; }
            .card { background: #f8fafc; padding: 15px; border-radius: 8px; margin-bottom: 20px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border-bottom: 1px solid #ddd; padding: 8px; text-align: left; }
          </style>
        </head>
        <body>
          <h1>Hisab Report</h1>
          <p>Profile: ${profileName}</p>
          <div class="card">
            <p><strong>${t.totalBalance}:</strong> ${formatCurrency(stats.balance)}</p>
            <p><strong>${t.netIncome}:</strong> ${formatCurrency(stats.totalIncome)}</p>
            <p><strong>${t.netExpense}:</strong> ${formatCurrency(stats.totalExpense)}</p>
          </div>
          <h3>Recent Expenses</h3>
          <table>
            <tr><th>Category</th><th>Amount</th></tr>
            ${expenseRows}
          </table>
        </body>
      </html>
    `;

    try {
      const { uri } = await Print.printToFileAsync({ html });
      await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (error) {
      Alert.alert("Error", "Could not generate or share PDF");
    }
  };

  const handleCopySummary = async () => {
    await safeCopy(getSummaryText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Modal visible={isOpen} transparent animationType="fade" onRequestClose={onClose}>
      <View className="flex-1 bg-black/60 justify-center items-center p-4">
        <View className="bg-white dark:bg-slate-800 rounded-2xl w-full max-w-md overflow-hidden max-h-[80%]">
          
          <View className="p-5 border-b border-slate-100 dark:border-slate-700 flex-row items-center justify-between bg-slate-50 dark:bg-slate-700">
            <View className="flex-row items-center gap-3">
              <Share2 size={20} color="#4f46e5" />
              <View>
                <Text className="text-lg font-bold text-slate-800 dark:text-white">{t.title}</Text>
              </View>
            </View>
            <TouchableOpacity onPress={onClose} className="p-2">
              <X size={20} color="#94a3b8" />
            </TouchableOpacity>
          </View>

          <ScrollView className="p-6 space-y-4">
            <TouchableOpacity 
              onPress={generateAndSharePDF}
              className="flex-row items-center gap-4 p-4 rounded-xl bg-indigo-50 dark:bg-indigo-900/10 border border-indigo-200 dark:border-indigo-800"
            >
              <Share2 size={20} color="#4f46e5" />
              <View>
                <Text className="font-semibold text-indigo-900 dark:text-indigo-100">{t.sharePdf}</Text>
                <Text className="text-xs text-indigo-700 dark:text-indigo-300">{t.sharePdfDesc}</Text>
              </View>
            </TouchableOpacity>

            <TouchableOpacity 
              onPress={handleCopySummary}
              className="flex-row items-center gap-4 p-3 rounded-xl border border-slate-200 dark:border-slate-700"
            >
              {copied ? <CheckCircle2 size={16} color="#10b981" /> : <Copy size={16} color="#64748b" />}
              <View>
                <Text className="font-medium text-slate-800 dark:text-slate-200">
                  {copied ? t.copied : t.copySummary}
                </Text>
                <Text className="text-xs text-slate-500 dark:text-slate-400">{t.summaryDesc}</Text>
              </View>
            </TouchableOpacity>
          </ScrollView>
        </View>
      </View>
    </Modal>
  );
};